she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('comment/<slug:slug>/', views.post_detail, name='post_detail'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include ('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('create-account/', views.CreateAccountView.as_view(), name='createAccount'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='user_profile'),
    path('profile/', views.LoggedInUserView.as_view()),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import datetime
from django.utils import timezone

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    content = models.TextField()
    img_url = models.URLField(max_length=500, blank=True, null=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name = "stories"
    )

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(
        NewsStory,
        on_delete=models.CASCADE, 
        related_name='comments'
        )
    author = models.CharField(max_length=200)
    comment_text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.comment_text

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, Comment


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'img_url']
        widgets = {
            'pub_date': forms.DateInput(
                format=('%m/%d/%Y'),
                attrs={
                    'class':'form-control',
                    'placeholder':'Select a date',
                    'type':'date'
                }
            ),
            'title': forms.TextInput(
                attrs={
                    'class':'title',
                    'placeholder':'...',
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class':'content',
                    'placeholder':'...',
                }
            )
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'comment_text')
        widgets = {
            'comment_text': forms.Textarea(
                attrs={
                    'class':'comment_text',
                    'placeholder':'...',
                }
            )
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.views import generic
from .models import NewsStory
from django.urls import reverse_lazy
from .forms import StoryForm, CommentForm
from django.shortcuts import render, get_object_or_404

class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

def post_detail(request, slug):
    template_name = 'news/post_detail.html'
    post = get_object_or_404(NewsStory, pk=slug)
    print(post)
    comments = post.comments.all()
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, template_name, {'post': post,
                                    'comments': comments,
                                    'new_comment': new_comment,
                                    'comment_form': comment_form})

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model

# Create your views here.
class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class UserProfileView(generic.DetailView):
    model = CustomUser
    template_name = 'users/user_profile.html'
    context_object_name = 'profile_user'

class LoggedInUserView(generic.TemplateView):
    template_name = 'users/user_profile.html'
    

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="submit">
</form>

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}  
{% load static %}  

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if all_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

{% for comment in comments %}
<div class="comments">
    <p class="comment_author">
        {{ comment.comment_text }}<br> 
        {{ comment.author }}<br>
        {{ comment.created_date }}
    </p>
    
</div>
{% endfor %}

<div class="comment-approval">
    {% if new_comment %}
    <div class="alert alert-success" role="alert">
        Your comment is awaiting moderation
    </div>
    {% else %}
        <h2>Leave us a comment:</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn-submit">Submit</button>
        </form>
{% endif %}
</div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content%}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        {% if not story.img_url %}
            <img src="http://picsum.photos/600">
        {% else %}
            <img src="{{ story.img_url }}">
        {% endif %}
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if not story.img_url %}
            <img src="http://picsum.photos/600">
        {% else %}
            <img src="{{ story.img_url }}">

        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She {Codes} News</title>
        <meta name="description" content="">
        <meta name="author" content="Megan O'Brien">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News </h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if user.is_authenticated %}
    <a href="{% url 'users:user_profile' request.user.id %}">{{ request.user }}</a>
    <a href="{% url 'news:newStory' %}">Contribute content</a>
    <a href="{% url 'logout' %}">Logout</a>
    

    {% else %}
    <a href="{% url 'login' %}">Login</a>
    <a href="{% url 'users:createAccount' %}">Signup</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}
{% load static %}  
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<h2>Create Account</h2>

<form method="post" class="create-account-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn-submit">Create Account</button>
</form>

{% endblock %}

she_codes_news/users/templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}  

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<h2>Profile</h2>

<div class="Profile-information" >
<p>Username: {{ profile_user.username }} <br>
Email: {{ profile_user.email }}  
</p>
    {% if user == profile_user %}
    <a href="{% url 'news:newStory' %}">Contribute content</a> 
    {% else %}
    <p>You must be logged in to create new stories</p>
    {% endif %}
</div>

<div id="all-stories">
    {% for story in profile_user.stories.all %}
        {% include "news/storyCard.html" with story=story position=forloop.counter %}
    {% endfor %}
</div>

{% endblock %}